name: CI/CD Pipeline
 
on:
  push:
    branches: ["main"]
  workflow_dispatch:
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  test:
    name: Testes e Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
 
      - name: Configurar Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
 
      - name: Instalar Dependências
        run: npm install
 
      - name: Executar Testes Unitários
        run: npm run test:unit
 
      - name: Executar Lint
        run: npm run lint
 
  build:
    name: Build da Aplicação
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
 
      - name: Configurar Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
 
      - name: Instalar Dependências
        run: npm install
 
      - name: Testes Unitários
        run: npm run test:unit
 
      - name: Build do Projeto
        run: npm run build
 
      - name: Salvar Artefato do Build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
 
  deploy:
    name: Deploy para GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
 
      - name: Baixar Artefato do Build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
 
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5
 
      - name: Fazer Upload do Artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
 
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
